### ISSUE TITLE
Legality of NetBooting

### ISSUE THREAD

**Issue by avenjamin** [bruienne/bsdpy#2]
Just came across this while reading the License agreement embedded within System Image Utility.
It seems to imply that you're only allowed to NetBoot from an "Apple-branded computer":

> E. System Imaging.
> 1. NetBoot Software. You may use the NetBoot software accessed through the Apple Software to **boot Apple-branded client computers from an Apple-branded computer** acting as a server that is running the Apple Software (“Apple Server”) for purposes of enabling such clients to access separate instances of the OS X desktop (and other Apple software and third party software) from the Apple Server, provided that each such Apple-branded client computer is licensed to run the version of the OS X software that is accessed as well as any other software.

I guess it's up to anyone using BSDpy to decide if they're comfortable to take the risk of running it on anything other than a Mac.

**Comment by bruienne** [comment]
I do appreciate the concern but I think it is unwarranted. I'll try to clarify. System Image Utility is not a part of BSDPy, it is an Apple-provided tool that assists in creating BSDP (NetBoot/NetInstall) compatible images (NBIs). Since the BSDPy project contains no Apple code but instead implements the open-sourced BSDP specification available from Apple it does not fall under Apple's EULA. You are correct that booting a EULA-covered OS X NBI on non-Apple hardware would violate the EULA but this applies universally to any computer booted via Apple's NetBoot service, BSDPy or any other tool that provides the Netboot service, like JAMF's NetSUS.
